name: CI

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Run install
      run: make install
      continue-on-error: false
    - name: Run download
      run: make download
      continue-on-error: false
    - name: Run build
      run: make build
      continue-on-error: false
    - name: Run delivery
      run: make delivery
      continue-on-error: false
