name: CI

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2.3.3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Run install
      shell: bash
      run: |
        ./script/install.sh
      continue-on-error: false
    - name: Run download
      shell: bash
      run: |
        ./script/download.sh
      continue-on-error: false
    - name: Run patch
      shell: bash
      run: |
        ./script/patch.sh
      continue-on-error: false
    - name: Run build
      shell: bash
      run: |
        ./script/build.sh
      continue-on-error: false
    - name: Run delivery
      shell: bash
      env:
        USER: ${{ secrets.JFROG_CLOUD_USER }}
        TOKEN: ${{ secrets.JFROG_CLOUD_TOKEN }}
      run: |
        ./script/delivery.sh
      continue-on-error: false
